services:
  backend:
    container_name: fastapi_atm-backend
    build: .
    restart: unless-stopped
    ports:
      - "4002:4002"
    volumes:
      - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "wait-for-it mysql:3306 -t 30 -- 
      uvicorn main:app --host 0.0.0.0 --port 4002"
    environment:
      - ENVIRONMENT=development

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: atm_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin123"]
      interval: 5s
      timeout: 10s
      retries: 10
  
  tests:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ENV=test
    command: >
      sh -c "wait-for-it mysql:3306 -t 30 -- 
      pytest tests -x -v"

volumes:
  mysql_data: